Update push.yml

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -7,24 +7,19 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
-      - name: Dump GitHub context
-        env:
-          GITHUB_CONTEXT: ${{ toJson(github) }}
-        run: echo "$GITHUB_CONTEXT"
       - name: Build the Docker image
         run: docker build . --tag eb:latest
-      - name: Tag the Docker image
-        run: |
-          docker tag eb:latest docker.pkg.github.com/judge2020/eb-cli-github-action/eb:$(date +%s)
-          docker tag eb:latest docker.pkg.github.com/judge2020/eb-cli-github-action/eb:${GITHUB_SHA}
-          docker tag eb:latest docker.pkg.github.com/judge2020/eb-cli-github-action/eb:${GITHUB_REF/refs\/heads\//} || echo "failsafe for non-conforming branch names"
-      - name: Tag latest if master
-        if: github.ref == 'refs/heads/master'
-        run: |
-          docker tag eb:latest docker.pkg.github.com/judge2020/eb-cli-github-action/eb:latest
-      - name: Login and push to GitHub Package Repository
+      - name: Login to GitHub Package Repository
         env:
           GH_TOKEN: ${{ secrets.GITHUB_PAT }}
         run: |
           docker login docker.pkg.github.com -u literallyanything -p ${GH_TOKEN}
-          docker push docker.pkg.github.com/judge2020/eb-cli-github-action/eb:latest
+      - name: Tag and push image
+        run: |
+          export DATE_TAG=$(date +%s)
+          docker tag eb:latest docker.pkg.github.com/judge2020/eb-cli-github-action/eb:${DATE_TAG}
+          docker push docker.pkg.github.com/judge2020/eb-cli-github-action/eb:${DATE_TAG}
+          docker tag eb:latest docker.pkg.github.com/judge2020/eb-cli-github-action/eb:${GITHUB_SHA}
+          docker push docker.pkg.github.com/judge2020/eb-cli-github-action/eb:${GITHUB_SHA}
+          docker tag eb:latest docker.pkg.github.com/judge2020/eb-cli-github-action/eb:${GITHUB_REF/refs\/heads\//} || echo "failsafe for non-conforming branch names"
+          docker push docker.pkg.github.com/judge2020/eb-cli-github-action/eb:${GITHUB_REF/refs\/heads\//} || echo "failsafe for non-conforming branch names"
